FROM node:alpine as builderApiMock
WORKDIR /tmp/mock
RUN npm init --yes
RUN npm add busboy express
RUN npm install

# ------------------------------------------------
FROM node:alpine as startApiMock
WORKDIR /usr/src/mock
COPY api-mock.js .
COPY --from=builderApiMock /tmp/mock/. ./
EXPOSE 8082
CMD ["node", "./api-mock.js"]
