version: '3.7'
services:
  api-mock:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.api-mock
    environment:
        - "PORT=8082"
    ports:
      - 8082:8082
  web:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080:8080
    depends_on:
      - api-mock
  cypress:
    network_mode: "host"
    image: "cypress/included:3.2.0"
    depends_on:
      - web
    environment:
      - CYPRESS_video=false
      - CYPRESS_baseUrl=http://127.0.0.1:8080
    working_dir: /e2e
    volumes:
    - ./:/e2e

