version: '3.7'
services:
  webamock:
    build:
      context: .
      dockerfile: Dockerfile.api-mock
    ports:
      - "8082:8082"
    expose:
      - "8082"
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - webamock
