FROM node:14
WORKDIR /usr/src/app
ENV API_URL=http://api-mock:8082
COPY . .
RUN apk update && apk add bash && apk add curl
RUN apk add --no-cache make gcc g++ python
RUN CYPRESS_INSTALL_BINARY=0 npm ci
RUN npm run build
EXPOSE 8080
CMD ["npm", "run", "server-test"]
