version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

jobs:
  build:
    working_directory: ~/pleiepengesoknad
    docker:
      - image: 'circleci/node:lts-stretch'
    steps:
      - checkout
      - run:
          name: Node Version
          command: node -v
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run build
      - nais/docker-deploy:
          image: navikt/pleiepengesoknad
  check:
    working_directory: ~/pleiepengesoknad
    docker:
      - image: 'circleci/node:lts-stretch'
    steps:
      - checkout
      - run:
          name: Node Version
          command: node -v
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-{{ checksum "package.json" }}
      - run: npm test
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run: npm run e2e
      - run: npm run build
  e2e:
    working_directory: ~/pleiepengesoknad
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: start-api-mock
          command: npm run start-api-mock
      - run:
          name: start-no-decorator
          command: npm run start-no-decorator
      - run:
          name: npm run cypress:ci
workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - check:
          filters:
            branches:
              ignore:
                - /dev-.*/
                - /snyk-.*/
      - build:
          context: NAIS deployment
          filters:
            branches:
              only:
                - master
                - /dev-.*/
                - /snyk-.*/
      - nais/deploy:
          name: dev-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepengesoknad
          image: navikt/pleiepengesoknad
          github-app-id: 35124
          nais-template: nais/dev-sbs.yml
          environment: dev-sbs
          team: dusseldorf
          filters:
            branches:
              only:
                - master
                - /dev-.*/
                - /snyk-.*/
          requires:
            - build
      - nais/deploy:
          name: prod-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepengesoknad
          image: navikt/pleiepengesoknad
          github-app-id: 35124
          nais-template: nais/prod-sbs.yml
          environment: prod-sbs
          team: dusseldorf
          filters:
            branches:
              only:
                - master
          requires:
            - build
