apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: pleiepengesoknad
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        periodSeconds: 5
        timeout: 1
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://pleiepengesoknad-q.nav.no
        - https://pleiepengesoknad.nais.oera-q.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: DEKORATOR_URL
          value: https://www.nav.no/dekoratoren/?simple=true
        - name: API_URL
          value: https://pleiepengesoknad-api-q.nav.no
        - name: PUBLIC_PATH
          value: https://pleiepengesoknad-q.nav.no
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://pleiepengesoknad-q.nav.no/soknad
        - name: UTILGJENGELIG
          value: "off"
        - name: TOGGLE_UTENLANDSOPPHOLD_I_PERIODEN
          value: "on"
        - name: TOGGLE_8_UKER
          value: "off"
        - name: TOGGLE_BEKREFT_OMSORG
          value: "off"
        - name: APPSTATUS_PROJECT_ID
          value: "ryujtq87"
        - name: APPSTATUS_DATASET
          value: "staging"




