apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: pleiepengesoknad
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://pleiepengesoknad.nav.no
        - https://pleiepengesoknad.nais.oera.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: http://appres.nav.no
        - name: API_URL
          value: https://pleiepengesoknad-api.nav.no
        - name: PUBLIC_PATH
          value: https://pleiepengesoknad.nav.no
        - name: LOGIN_URL
          value: https://loginservice.nav.no/login?redirect=https://pleiepengesoknad.nav.no/soknad/velkommen
        - name: TOGGLE_LANGUAGE
          value: "on"
        - name: UTILGJENGELIG
          value: "off"
        - name: TOGGLE_UTENLANDSOPPHOLD_I_PERIODEN
          value: "off"
        - name: TOGGLE_FERIEUTTAK
          value: "off"
        - name: TOGGLE_FRILANS
          value: "off"
        - name: TOGGLE_SELVSTENDIG
          value: "off"
        - name: TOGGLE_8_UKER
          value: "off"
        - name: TOGGLE_BEKREFT_OMSORG
          value: "off"
        - name: UTVIDET_KVITTERING
          value: "off"
          


