# This workflow trigger on push to any branch
name: CI / CD
on:
  deployment:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test code
        run: |
          npm ci
          npm run test
          npm run e2e-docker-compose

  build-code-and-push-docker:
    name: Build code and push docker image
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') || github.event.deployment.payload.triggered # Build and push docker if branch is either master or dev-*
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build code
        run: |
          npm i
          npm run build
      - name: Create Docker tag
        env:
          NAME: pleiepengesoknad
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Build Docker image
        run: |
          docker build -t $(cat .docker_image):$(cat .docker_tag) .
      - name: Login to Github Package Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login -u ${GITHUB_REPOSITORY} -p ${DOCKER_PASSWORD} docker.pkg.github.com
      - name: Push Docker image
        run: "docker push $(cat .docker_image):$(cat .docker_tag)"
      - name: pass image file to next job.
        uses: actions/upload-artifact@v1
        with:
          name: docker_image
          path: .docker_image
      - name: pass tag file to next job.
        uses: actions/upload-artifact@v1
        with:
          name: docker_tag
          path: .docker_tag

  deploy:
    name: Deploy environment
    if: github.event.deployment.payload.triggered # Deploy if triggered by cli
    needs: build-code-and-push-docker # Depends on build-code-and-push-docker job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Download the image and tag file to use for the deployment cli.
      - name: Download image file
        uses: actions/download-artifact@v1
        with:
          name: docker_image
      - name: Download tag file
        uses: actions/download-artifact@v1
        with:
          name: docker_tag
      - name: unpack
        run: |
          cp docker_image/.docker_image .
          cp docker_tag/.docker_tag .
      - name: debug
        run: ls -la
      - name: deploy to environment
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: ${{ github.event.deployment.environment }}
          team: dusseldorf
          resources: ${{  format('nais/{0}.yml', github.event.deployment.environment) }}

  deploy-dev-sbs:
    name: deploy-dev-sbs
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') # Build and push docker if branch is either master or dev-*
    needs: build-code-and-push-docker # Depends on build-code-and-push-docker job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Download the image and tag file to use for the deployment cli.
      - name: Download image file
        uses: actions/download-artifact@v1
        with:
          name: docker_image
      - name: Download tag file
        uses: actions/download-artifact@v1
        with:
          name: docker_tag
      - name: unpack
        run: |
          cp docker_image/.docker_image .
          cp docker_tag/.docker_tag .
      - name: deploy to dev-sbs
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-sbs
          team: dusseldorf
          resources: nais/dev-sbs.yml

  deploy-prod-sbs:
    name: deploy-prod-sbs
    if: startsWith(github.ref, 'refs/heads/master') # Build and push docker if branch is either master or dev-*
    needs: build-code-and-push-docker # Depends on build-code-and-push-docker job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Download the image and tag file to use for the deployment cli.
      - name: Download image file
        uses: actions/download-artifact@v1
        with:
          name: docker_image
      - name: Download tag file
        uses: actions/download-artifact@v1
        with:
          name: docker_tag
      - name: unpack
        run: |
          cp docker_image/.docker_image .
          cp docker_tag/.docker_tag .
      - name: deploy to prod-sbs
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-sbs
          team: dusseldorf
          resources: nais/prod-sbs.yml
