# This workflow trigger on push to any branch
name: CI / CD
on:
    push:
        paths-ignore:
            - '**.md'
            - '.gitignore'
            - 'LICENCE'
            - 'CODEOWNERS'
        branches:
            - '*'

env:
    IMAGE: ghcr.io/${{ github.repository }}/pleiepengesoknad-gcp:${{ github.sha }}
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    test:
        name: Test Code with Jest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Test code
              run: |
                  CYPRESS_INSTALL_BINARY=0
                  npm ci
                  npm run test
    e2e:
        name: End to End testing with Cypress
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Setup kernel for react + node, increase watchers
              run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
            - name: Run E2E with
              run: npm run e2e-docker-compose

    build-code-and-push-docker-gcp:
        name: Build code and push docker image gcp
        if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') || github.event.deployment.payload.triggered # Build and push docker if branch is either master or dev-*
        needs: [test, e2e]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Cache NPM dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache-
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: build code
              run: |
                  npm i --legacy-peer-deps
                  npm run build
            - name: Build and publish Docker image
              run: |
                  docker build --tag ${IMAGE} . -f Dockerfile
                  echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
                  docker push ${IMAGE}

    deploy-prod-gcp:
        name: Deploy-prod-gcp
        if: startsWith(github.ref, 'refs/heads/master')
        needs: build-code-and-push-docker-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/naiserator.yml
                  VARS: nais/prod-gcp.json
