name: Deploy branch to dev

on:
    workflow_dispatch:
        secrets:
            NAIS_DEPLOY_APIKEY:
                description: Nais deploy APIKEY
                required: false

env:
    IMAGE: ghcr.io/${{ github.repository }}/pleiepengesoknad-gcp:${{ github.sha }}
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build-code-and-push-docker-gcp:
        name: Build code and push docker image gcp
        # needs: [test, e2e]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Cache NPM dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache-
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: build code
              run: |
                  npm i
                  npm run build
            - name: Build and publish Docker image
              run: |
                  docker build --tag ${IMAGE} . -f Dockerfile
                  echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
                  docker push ${IMAGE}

    deploy-dev-gcp:
        name: Deploy to dev-gcp
        needs: build-code-and-push-docker-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/naiserator.yml
                  VARS: nais/dev-gcp.json
