name: Dispatch - deploy branch to dev

on:
  workflow_dispatch:
    secrets:
        NAIS_DEPLOY_APIKEY:
            description: Nais deploy APIKEY
            required: false

jobs:
    deploy-to-dev:
        name: Deploy to dev
        uses: navikt/sif-brukerdialog/.github/workflows/deploy-branch-to-dev.yml@main
        secrets:
            NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
